import React, { useState } from 'react';
import { useHealthStore } from '../../context/HealthStoreContext';
import { Card, CardBody, CardHeader } from '../../components/Card';
import { Badge } from '../../components/Badge';
import { Button } from '../../components/Button';
import { FileText, Download, CheckCircle, Clock } from 'lucide-react';
import { Modal } from '../../components/Modal';

export const MedicalRecords: React.FC = () => {
  const { diagnostics } = useHealthStore();
  const [viewReport, setViewReport] = useState<typeof diagnostics[0] | null>(null);

  // Get data specifically for Rajesh Kumar (P-101)
  const patientId = 'P-101';
  const myDiagnostics = diagnostics.filter(d => d.patientId === patientId);

  const handleDownload = (reportName: string) => {
    alert(`Downloading ${reportName}_swasthya_report.pdf ...`);
  };

  return (
    <div className="space-y-6">
      
      {/* Title */}
      <div>
        <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-slate-900 dark:text-white">Diagnostic & Lab Reports</h1>
        <p className="text-xs text-slate-500">Access reports generated by primary health centres and referral hospitals linked to your ABHA health account.</p>
      </div>

      {/* Reports Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {myDiagnostics.map(diag => (
          <Card key={diag.id}>
            <CardBody className="space-y-4">
              <div className="flex justify-between items-start gap-4">
                <div className="flex gap-3">
                  <div className="h-10 w-10 bg-indigo-50 dark:bg-indigo-950/20 text-indigo-600 rounded-lg flex items-center justify-center">
                    <FileText className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="font-bold text-sm text-slate-900 dark:text-white leading-tight">{diag.testName}</h3>
                    <p className="text-[10px] text-slate-500 mt-1">🏥 {diag.facilityName}</p>
                  </div>
                </div>
                <Badge color={diag.status === 'Completed' ? 'success' : 'warning'}>
                  {diag.status}
                </Badge>
              </div>

              {diag.status === 'Completed' && diag.result && (
                <div className="bg-slate-50 dark:bg-slate-900 p-3 rounded-lg border border-slate-150 dark:border-slate-800 text-xs">
                  <p className="font-semibold text-slate-650 dark:text-slate-350">Diagnostic Finding:</p>
                  <p className="text-slate-800 dark:text-slate-200 font-medium mt-1">{diag.result}</p>
                  {diag.normalRange && (
                    <p className="text-[10px] text-slate-500 mt-2">Reference standard: {diag.normalRange}</p>
                  )}
                </div>
              )}

              {diag.status === 'Pending' && (
                <div className="bg-amber-50/50 dark:bg-amber-950/10 p-3 rounded-lg border border-amber-200/50 dark:border-amber-900/30 text-xs flex items-center gap-2">
                  <Clock className="h-4 w-4 text-amber-500" />
                  <span className="text-slate-600 dark:text-slate-400">Awaiting diagnostic queue clearance. Expected in 24 hrs.</span>
                </div>
              )}

              <div className="pt-2 border-t border-slate-50 dark:border-slate-800 flex justify-between items-center text-[10px]">
                <span className="text-slate-400">Dated: {diag.date}</span>
                {diag.status === 'Completed' ? (
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={() => setViewReport(diag)}>View Details</Button>
                    <Button variant="secondary" size="sm" onClick={() => handleDownload(diag.testName)} leftIcon={<Download className="h-3 w-3" />} />
                  </div>
                ) : (
                  <span className="font-semibold text-amber-600 dark:text-amber-400">Scheduled Queue</span>
                )}
              </div>
            </CardBody>
          </Card>
        ))}
      </div>

      {/* View Details Modal */}
      {viewReport && (
        <Modal 
          isOpen={!!viewReport} 
          onClose={() => setViewReport(null)}
          title={viewReport.testName}
        >
          <div className="space-y-6">
            <div className="grid grid-cols-2 gap-4 text-xs border-b border-slate-100 dark:border-slate-800 pb-4">
              <div>
                <span className="text-slate-450 block text-[10px] uppercase font-bold">Patient Name</span>
                <span className="font-bold text-slate-850 dark:text-slate-100">Rajesh Kumar</span>
              </div>
              <div>
                <span className="text-slate-450 block text-[10px] uppercase font-bold">ABHA Account</span>
                <span className="font-mono font-bold text-slate-850 dark:text-slate-100">91-8273-9281-2831</span>
              </div>
              <div>
                <span className="text-slate-450 block text-[10px] uppercase font-bold">Origin Facility</span>
                <span className="font-bold text-slate-850 dark:text-slate-100">{viewReport.facilityName}</span>
              </div>
              <div>
                <span className="text-slate-450 block text-[10px] uppercase font-bold">Date of Report</span>
                <span className="font-bold text-slate-850 dark:text-slate-100">{viewReport.date}</span>
              </div>
            </div>

            <div className="space-y-3">
              <h4 className="font-bold text-sm text-slate-900 dark:text-white">Diagnostic Examination Report</h4>
              <div className="bg-slate-50 dark:bg-slate-900 p-4 rounded-xl border border-slate-150 dark:border-slate-800 text-xs leading-relaxed text-slate-700 dark:text-slate-350">
                {viewReport.result}
              </div>
            </div>

            <div className="bg-hospital-50 dark:bg-hospital-950/20 text-hospital-700 dark:text-hospital-450 text-[10px] p-3 rounded-lg border border-hospital-200 dark:border-hospital-900 flex items-center gap-2">
              <CheckCircle className="h-4 w-4" />
              <span>Report verified and digitally signed by Clinical Pathology Desk.</span>
            </div>

            <div className="flex justify-end space-x-2">
              <Button variant="secondary" onClick={() => setViewReport(null)}>Close</Button>
              <Button variant="primary" onClick={() => handleDownload(viewReport.testName)} leftIcon={<Download className="h-4 w-4" />}>
                Download PDF
              </Button>
            </div>
          </div>
        </Modal>
      )}

    </div>
  );
};
