const MedicalRecord = require('../models/MedicalRecord');
const Prescription = require('../models/Prescription');
const LabReport = require('../models/LabReport');
const ApiError = require('../utils/ApiError');
const asyncHandler = require('../utils/asyncHandler');
const { currentPatient, currentDoctor, requirePatientAccess } = require('../utils/access');
const id = prefix => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`;

exports.createRecord = asyncHandler(async (req, res, next) => { const doctor = await currentDoctor(req.user._id); if (!doctor) return next(ApiError.forbidden('Doctor access required')); const record = await MedicalRecord.create({ ...req.body, doctor: doctor._id, facility: req.body.facility || doctor.facility, consultationDate: req.body.consultationDate || new Date(), createdBy: req.user._id }); res.status(201).json({ success: true, message: 'Medical record created', data: record }); });
exports.recordsForPatient = asyncHandler(async (req, res) => { await requirePatientAccess(req, req.params.patientId); const data = await MedicalRecord.find({ patient: req.params.patientId }).sort({ consultationDate: -1 }); res.json({ success: true, message: 'Medical records retrieved', data }); });
exports.getRecord = asyncHandler(async (req, res, next) => { const data = await MedicalRecord.findById(req.params.id); if (!data) return next(ApiError.notFound('Medical record not found')); await requirePatientAccess(req, data.patient); res.json({ success: true, message: 'Medical record retrieved', data }); });
exports.updateRecord = asyncHandler(async (req, res, next) => { const doctor = await currentDoctor(req.user._id); const record = await MedicalRecord.findById(req.params.id); if (!record) return next(ApiError.notFound('Medical record not found')); if (req.user.role !== 'admin' && (!doctor || record.doctor.toString() !== doctor._id.toString())) return next(ApiError.forbidden('Not allowed to update this record')); Object.assign(record, req.body, { updatedBy: req.user._id }); await record.save(); res.json({ success: true, message: 'Medical record updated', data: record }); });
exports.createPrescription = asyncHandler(async (req, res, next) => { const doctor = await currentDoctor(req.user._id); if (!doctor) return next(ApiError.forbidden('Doctor access required')); const data = await Prescription.create({ ...req.body, doctor: doctor._id, prescriptionNumber: id('RX'), createdBy: req.user._id }); res.status(201).json({ success: true, message: 'Prescription created', data }); });
exports.myPrescriptions = asyncHandler(async (req, res) => { const patient = await currentPatient(req.user._id); const data = await Prescription.find(patient ? { patient: patient._id } : { doctor: (await currentDoctor(req.user._id))._id }).sort({ prescriptionDate: -1 }); res.json({ success: true, message: 'Prescriptions retrieved', data }); });
exports.getPrescription = asyncHandler(async (req, res, next) => { const data = await Prescription.findById(req.params.id); if (!data) return next(ApiError.notFound('Prescription not found')); await requirePatientAccess(req, data.patient); res.json({ success: true, message: 'Prescription retrieved', data }); });
exports.createLab = asyncHandler(async (req, res, next) => { if (!['doctor', 'health_worker', 'admin'].includes(req.user.role)) return next(ApiError.forbidden('Clinical staff access required')); const data = await LabReport.create({ ...req.body, reportNumber: id('LAB'), createdBy: req.user._id }); res.status(201).json({ success: true, message: 'Lab report created', data }); });
exports.myLabs = asyncHandler(async (req, res) => { const patient = await currentPatient(req.user._id); const data = await LabReport.find({ patient: patient._id }).sort({ reportDate: -1 }); res.json({ success: true, message: 'Lab reports retrieved', data }); });
exports.labsForPatient = asyncHandler(async (req, res) => { await requirePatientAccess(req, req.params.patientId); const data = await LabReport.find({ patient: req.params.patientId }).sort({ reportDate: -1 }); res.json({ success: true, message: 'Lab reports retrieved', data }); });
