const Queue = require('../models/Queue');
const Appointment = require('../models/Appointment');
const ApiError = require('../utils/ApiError');
const asyncHandler = require('../utils/asyncHandler');
const { currentPatient, currentDoctor } = require('../utils/access');
const socketManager = require('../config/socket');
const today = () => new Date(new Date().toDateString());
const room = q => `queue:${q.doctor}:${q.facility}`;
const emit = (q, event, data) => { const io = socketManager.getIO(); if (io) io.to(room(q)).emit(event, data); };

exports.checkIn = asyncHandler(async (req, res, next) => {
 const patient = await currentPatient(req.user._id); const appointment = await Appointment.findById(req.params.appointmentId);
 if (!patient || !appointment || appointment.patient.toString() !== patient._id.toString()) return next(ApiError.forbidden('Not allowed to check in'));
 if (!['BOOKED', 'CONFIRMED'].includes(appointment.status)) return next(ApiError.badRequest('Appointment cannot be checked in'));
 let queue = await Queue.findOne({ doctor: appointment.doctor, facility: appointment.facility, queueDate: { $gte: today(), $lt: new Date(today().getTime() + 86400000) }, isActive: true });
 if (!queue) queue = await Queue.create({ doctor: appointment.doctor, facility: appointment.facility, queueDate: today() });
 if (queue.patients.some(p => p.appointment.toString() === appointment._id.toString())) return next(ApiError.conflict('Already checked in'));
 const position = queue.patients.filter(p => p.status === 'waiting').length + 1; const token = `A-${String((queue.totalPatients || 0) + 1).padStart(3, '0')}`;
 queue.patients.push({ appointment: appointment._id, patient: patient._id, tokenNumber: token, position }); queue.totalPatients += 1; queue.patientsWaiting += 1; queue.nextToken = token; await queue.save();
 appointment.status = 'IN_QUEUE'; appointment.tokenNumber = token; appointment.queuePosition = position; appointment.estimatedWaitingTime = (position - 1) * 15; await appointment.save();
 const data = { tokenNumber: token, position, patientsAhead: position - 1, estimatedWaitingTime: (position - 1) * 15 }; emit(queue, 'queueUpdated', data); res.status(201).json({ success: true, message: 'Checked into queue', data });
});
exports.status = asyncHandler(async (req, res, next) => { const appointment = await Appointment.findById(req.params.appointmentId); const patient = await currentPatient(req.user._id); if (!appointment || !patient || appointment.patient.toString() !== patient._id.toString()) return next(ApiError.forbidden('Not allowed')); const queue = await Queue.findOne({ 'patients.appointment': appointment._id }); const entry = queue && queue.patients.find(p => p.appointment.toString() === appointment._id.toString()); if (!entry) return next(ApiError.notFound('Queue entry not found')); const ahead = queue.patients.filter(p => p.status === 'waiting' && p.position < entry.position).length; res.json({ success: true, message: 'Queue status retrieved', data: { tokenNumber: entry.tokenNumber, status: entry.status, patientsAhead: ahead, estimatedWaitingTime: ahead * 15, currentToken: queue.currentToken } }); });
exports.next = asyncHandler(async (req, res, next) => { const doctor = await currentDoctor(req.user._id); if (!doctor) return next(ApiError.forbidden('Doctor access required')); const queue = await Queue.findOne({ doctor: doctor._id, isActive: true }).sort({ queueDate: -1 }); if (!queue) return next(ApiError.notFound('Active queue not found')); const entry = queue.patients.find(p => p.status === 'waiting'); if (!entry) return next(ApiError.notFound('No waiting patients')); entry.status = 'called'; queue.currentToken = entry.tokenNumber; queue.lastCalledToken = entry.tokenNumber; queue.lastCalledAt = new Date(); await queue.save(); await Appointment.findByIdAndUpdate(entry.appointment, { status: 'IN_PROGRESS', consultationStartTime: new Date() }); const data = { tokenNumber: entry.tokenNumber, appointmentId: entry.appointment }; emit(queue, 'patientCalled', data); emit(queue, 'queueUpdated', data); res.json({ success: true, message: 'Next patient called', data }); });
exports.complete = asyncHandler(async (req, res, next) => { const doctor = await currentDoctor(req.user._id); const appointment = await Appointment.findById(req.params.appointmentId); if (!doctor || !appointment || appointment.doctor.toString() !== doctor._id.toString()) return next(ApiError.forbidden('Not allowed')); const queue = await Queue.findOne({ 'patients.appointment': appointment._id }); const entry = queue && queue.patients.find(p => p.appointment.toString() === appointment._id.toString()); if (!entry) return next(ApiError.notFound('Queue entry not found')); entry.status = 'completed'; queue.patientsWaiting = Math.max(0, queue.patientsWaiting - 1); queue.patientsConsulted += 1; await queue.save(); appointment.status = 'COMPLETED'; appointment.consultationEndTime = new Date(); await appointment.save(); emit(queue, 'consultationCompleted', { appointmentId: appointment._id, tokenNumber: entry.tokenNumber }); res.json({ success: true, message: 'Consultation completed', data: appointment }); });
